sudo: false
language: python
python:
  - "3.6"
install:
  - pip install flake8>=3.5.0
  - pip install -r requirements.txt
script:
  - flake8 --ignore=F401
  - python -W ignore -m unittest discover
cache: pip
